## Configurations for Netlify
## This repo is hosted at rawtangoandchaos.netlify.com

[Settings]
ID = "rawtangoandchaos"

[build]
  #base = "/"
  #publish = "project/build-output/"
  #command = "echo 'default context'"

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

[[redirects]]
  from = "/old-path"
  to = "/new-path"

  # The default HTTP status code is 301, but you can define a different one.
  status = 302

  # By default, redirects won't be applied if there's a file with the same 
  # path as the one defined in the `from` property. Setting `force` to `true` 
  # will make the redirect rule take precedence over any existing files.
  #force = true


# The following redirect is intended for use with most SPAs that handle
# routing internally.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/test/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-key header rules are expressed with multi-line strings.
    Link = '''
    </assets/css/base.css>; rel=preload; as=style, \
    </assets/css/base2.css>; rel=preload; as=style, \
    </assets/css/base3.css>; rel=preload; as=style'''

    # Basic-Auth allows you to password protect your whole site. 
    # Only available to paid accounts.
    # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
